# Site
name: "Học Bài Cùng Con"
title: "Học Bài Cùng Con"
description: "Lưu trữ các video, tài liệu dạy và học môn Toán THPT."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: #"https://hocbaicungcon.edu.vn" #/mediumish-theme-jekyll
google_analytics: 'UA-46278016-1'
disqus: 'hocbaicungcon'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  bar:
    name: Phan V. Phương
    display_name: Phương PV.
    gravatar: c95bbf78f5b02f98f60d3e3c7006da32
    email: hocbaicungcon@gmail.com
    web: https://hocbaicungcon.edu.vn
    twitter: https://twitter.com/hocbaicungcon
    description: "Giáo viên Toán trường THPT Xuân Trường B - Nam Định. Có những hiểu biết nhất định về Toán THPT, các phương pháp dạy học, SEO, LaTEX, Python, Ruby on Rail..."


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
